aws:
  s3:
    access-key: ${AWS_ACCESS_KEY:test}
    secret-key: ${AWS_SECRET_KEY:test}
    region: ${AWS_S3_REGION:us-bogus-1}
    bucket: ${AWS_S3_BUCKET:bogus}

idx:
  location: ./cat-idx
  categories:
    - key: carRepair
      title: Car repair
      keywords: "гума шини ремонт авто ходова колеса акумулятор"
    - key: drones
      title: Drones
      keywords: "mavic mavik мавік autel лелека дрон коптер квадрокоптер drone"
    - key: electronics
      title: Electronic equipment
      keywords: "ноутбук laptop tablet планшет комп'ютер монітор батарея"
    - key: kits
      title: First aid kits
      keywords: "ліки турнікет бандаж аптечка"
    - key: nightVisionDevices
      title: Night vision devices
      keywords: "пнб тепловізор cyclops циклоп pvs тєплак тєплік нічник прилад нічного бачення"
    - key: other
      title: Other aid
      keywords: "холодильник грілка лопата плащ дощовик цигарки сигарети спальник спальний мішок"
    - key: powerGenerator
      title: Power generator
      keywords: "зарядна станція генератор ecoflow екофлоу еклофло anker павербанк powerbank power bank"
    - key: radios
      title: Radio transmitters
      keywords: "рація старлінк starlink антена реб глушилка"
    - key: equipment
      title: Equipment
      keywords: "шолом плитоноска броня бронепластина форма екіп рюкзак взуття бреці рукавиці саперський набір бінокль вуха навушники глушник планка пікатіні штани убакс підсумка"

source:
  t-key: ${TRELLO_KEY:test}
  t-token: ${TRELLO_TOKEN:test}
  t-board-id: ${TRELLO_BOARD_ID:test}

g-translator:
  url: ${G_TRANSLATOR_URL:"https://example.com"}

quarkus:
  s3:
    devservices:
      enabled: false
